# Generated by Django 5.0.7 on 2024-09-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ItemEntry',
        ),
    ]
